### PR TITLE
45 accessibiity fixes

### LINKED ISSUE #45: Accessibility Test
Running 4-5 tests suggested by Mark

### PR DESCRIPTION
**Pull request by admivsn**
This is everything APART from the play button fixed, not sure if we want to merge yet or not?

### CODE REVIEW

**Review by nhsbsa-kaygo — APPROVED** [review]
ADD to this branch:
Add nhs_grid mod
Change play button to shiny input to fix the critical error
Reflect Matt's review

**Comment by nhsbsa-kaygo** [comment]
[LIS Feedback MW Feb22.docx](https://github.com/nhsbsa-data-analytics/lowIncomeSchemeScrollytellR/files/8040685/LIS.Feedback.MW.Feb22.docx)

File: R/mod_08_spotlight_students.R [hunk 1]
```diff
@@ -306,7 +306,9 @@ mod_08_spotlight_students_server <- function(id) {
       student_individuals_by_region_df %>%
         dplyr::filter(
           ACADEMIC_YEAR == input$slider_student_individuals_by_region
-        )
+        ) %>%
```
Comment (nhsbsa-kaygo) [inline R/mod_08_spotlight_students.R]: @admivsn, you may have a neater solution. It removed error message for the WAVE tool but DevAx still shows as an needs review error.
